"""Cria tabela de fornecedor cliente

Revision ID: 55425dec6176
Revises: f4ca06f6c0a0
Create Date: 2025-07-30 15:36:33.047690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55425dec6176'
down_revision: Union[str, Sequence[str], None] = 'f4ca06f6c0a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedor_cliente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('contas_a_pagar_e_receber', 'descricao',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('contas_a_pagar_e_receber', 'valor',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(),
               nullable=True)
    op.alter_column('contas_a_pagar_e_receber', 'tipo',
               existing_type=postgresql.ENUM('PAGAR', 'RECEBER', name='tipoconta'),
               type_=sa.String(length=30),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contas_a_pagar_e_receber', 'tipo',
               existing_type=sa.String(length=30),
               type_=postgresql.ENUM('PAGAR', 'RECEBER', name='tipoconta'),
               nullable=False)
    op.alter_column('contas_a_pagar_e_receber', 'valor',
               existing_type=sa.Numeric(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('contas_a_pagar_e_receber', 'descricao',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_table('fornecedor_cliente')
    # ### end Alembic commands ###
